name: WorldCaster
version: '1.0.5'
main: me.omaromar93.worldCaster.WorldCasterS
depend:
  - WorldChatter
api-version: '1.13'
authors: [ OmarOmar93 ]
description: Standalone Broadcast Add-on for WorldChatter!
commands:
  broadcast:
    description: Sends a message to all places.
    aliases:
      - b
      - bc